CREATE TABLE page (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  is_root BOOL DEFAULT FALSE,
  parent_id INT(11) DEFAULT NULL,
  sorting INT(11) DEFAULT NULL,
  title VARCHAR(255),
  path VARCHAR(255),
  sitemap_change_freq VARCHAR(255),
  sitemap_priority DECIMAL(3,2),
  p01 VARCHAR(255) DEFAULT '',
  p02 VARCHAR(255) DEFAULT NULL,
  p03 VARCHAR(255) DEFAULT NULL
);